game_settings:
   print_player_tab:
      enable: true # If True, it will print end game tab at least for the player that finished, Default: True
      for_all_players: true # If True, it will print the end game tab for all players in the game (have to be False if print_player_tab.enable if False), Default: True
   end_game_when_one_remains: false # If True, the game ends if only one player remains (do not enable if the game contains only one player), Default: False
   spreadplayers:
      enable: false # True: when start the game, spread players., Default: False
      minimum_distance: 500 # for spreadplayer command, minimum distance between player, Default: 500
      minimum_radius: 1000 # for spreadplayer command, minimum radius must be > minimum_distance parameter, Default: 1000
   saturation: false # True: give infinite saturation effect to all players, Default: False
   rewards: true # True: give reward after each age, Default: True
   passive:
      all: false # True: pvp disabled and open other player box is disable, Default: False
      team: false # True: pvp between team mates is disabled, Default: False
   time:
      start: 4 # minutes, Default: 4
      added: 2 # minutes added to start_time after each age, Default: 2
   last_age: "Mythic_Age" # Last Age to finish the game, can be any of ages.json ages, Default : Mythic_Age
   target_per_age: 5 # number of target to complete and move to the next age, min: 1, Default: 5
   lang: "en" # Lang for all players, Default: "en"
   level: "EASY" # Game difficulty, can be any of the levels.json levels, Default: EASY
   skip:
      enable: true # allow player to skip target if they are after 2nd target of current age, Default: true
      age: "Classic_Age" # First age that allow target skipping, can be any of ages.json ages, Default: "Classic_Age"
   custom_crafts: true # If True, allow players to use not mandatory custom crafts, Default: True
   team:
      enable: false # Define if team are allowed or not, Default: False
      size: 2 # Size of a team, Default: 2
   modes:
      same: false # If true, players will have same target, Default: False
      double: false # If true, players will be able to choose between two target instead of one, Default: false
      sbtt:
         enable: false # If true, players will be able to validate without using there actual target, Default: false
         amount: 4 # Amount of target randomly selected to make Templates (must be between 1 and 9 included), Default: 4
   xp_max:
      end_teleporter: 5 # Amount of xp level needed to use EndTeleporter (must be between 1 and 10 included), Default: 5
      overworld_teleporter: 10 # Amount of xp level needed to use OverworldTeleporter (must be between 1 and 20 included), Default: 10
      coral_compass: 20 # Amount of xp level needed to use CoralCompass (must be between 1 and 30 included), Default: 20